"""Script template for generated conversion scripts."""

SCRIPT_TEMPLATE = '''"""
Canopy Conversion Script
Generated: {timestamp}
Job ID: {job_id}
Source: {source_description}
Target: {target_table}

Auto-generated by Canopy's agentic pipeline.
You can inspect, edit, version control, and re-run this script independently.

Usage:
    python {filename} input.csv output.csv
"""
import csv
import re
import sys
from datetime import date, datetime
from decimal import Decimal, InvalidOperation


{transform_func}


{validate_func}


# --- Standalone runner ---
if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python {filename} <input.csv> <output.csv>")
        sys.exit(1)

    input_path, output_path = sys.argv[1], sys.argv[2]
    success_count, error_count = 0, 0

    with open(input_path, newline="", encoding="utf-8") as fin:
        reader = csv.DictReader(fin)
        rows = []
        for i, row in enumerate(reader):
            try:
                result = transform(row)
                if result is not None:
                    warnings = validate(result)
                    if warnings:
                        print(f"Row {{i}}: {{warnings}}", file=sys.stderr)
                    rows.append(result)
                    success_count += 1
            except Exception as e:
                error_count += 1
                print(f"Row {{i}} error: {{e}}", file=sys.stderr)

    if rows:
        with open(output_path, "w", newline="", encoding="utf-8") as fout:
            writer = csv.DictWriter(fout, fieldnames=rows[0].keys())
            writer.writeheader()
            writer.writerows(rows)

    print(f"Done: {{success_count}} transformed, {{error_count}} errors")
'''

DEFAULT_VALIDATE_FUNC = '''def validate(row: dict) -> list[str]:
    """Validate a transformed row. Returns list of warnings (empty = OK)."""
    return []'''
